single envelope changes
HumanCellAtlas/ingest-state-tracking pull request #6
Opened 2019-11-07 15:45 UTC by prabh-t

2019-11-07 15:55 UTC, rolando-ebi approved these changes

2019-11-07 15:57 UTC, MightyAx requested changes
Please delete the comments for disabling old features, this will help with maintainability in the future.
Other than that, Looks Good To Me.

2019-11-07 15:57 UTC, MightyAx commented on src/main/java/org/humancellatlas/ingest/messaging/Constants.java
> +        //public static final String DOCUMENT_UPDATE = "ingest.state-tracking.metadata.update.queue";
just delete code rather than commenting it out.
Can we can the team to confirm your assertion that there aren't used?

2019-11-07 15:57 UTC, MightyAx commented on src/main/java/org/humancellatlas/ingest/messaging/QueueConfig.java
> +     */
Please delete instead of commenting.

2019-11-07 15:57 UTC, MightyAx commented on src/main/java/org/humancellatlas/ingest/messaging/QueueConfig.java
> +    */
Please delete instead of commenting.

2019-11-07 15:59 UTC, aaclan-ebi approved these changes
There are some commented out codes that could be removed. But other than that, this looks good.

2019-11-07 15:59 UTC, aaclan-ebi commented on src/main/java/org/humancellatlas/ingest/messaging/Constants.java
> +        //not used
clean up

2019-11-07 15:59 UTC, aaclan-ebi commented on src/main/java/org/humancellatlas/ingest/messaging/QueueConfig.java
> +    /**
clean up

2019-11-13 15:07 UTC, prabh-t commented on src/main/java/org/humancellatlas/ingest/messaging/QueueConfig.java
> +    /**
OK. all suggested clean up now done.

2019-11-13 15:17 UTC, MightyAx approved these changes

2019-11-13 15:20 UTC, merged